spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql은 콘솔에 찍힘
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    # Logger에 sql문이 찍힌다.
    org.hibernate.SQL: debug
    p6spy: info
